//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCalculator.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryId { get; set; }
        public string MathExpresion { get; set; }
        public string Result { get; set; }
        public System.DateTime Time { get; set; }
        public byte IsDeleted { get; set; }
    }
}
